 language: ruby
rvm : 2.2.5

bundler_args: --without development --development

cache: bundler

addons: 
   postgresql: "9.3"
  
 before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate RAILS_ENV=test
 
 script:
  - bundle exec rspec spec
 dist: precise