language: ruby
 rvm:
  - 2.2.5

 bundler_args: --without development --development
 
 cache: bundler
 
 addons:
   postgresql: "9.3"
  
 before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate RAILS_ENV=test
 
 script:
  - bundle exec rspec spec
 dist: precise
 
 deploy:
  provider: heroku
  api_key:
    secure: 1a:34:f0:6c:0c:d2:2e:d4:80:0f:9c:f8:ea:1f:dc:0c ubuntu@kichiobookman-stressshredder-5032839
    app: calm-garden-50645
  on:
    repo: chubachi-pt-2017/StressShredder
  run:
    - "rake db:migrate"
    - restart
    - "rake cleanup"
 
 
 